Update templates

diff --git a/userpatches-jethub/gha/chunks/550.per-chunk-artifacts_job.yaml b/userpatches-jethub/gha/chunks/550.per-chunk-artifacts_job.yaml
--- a/userpatches-jethub/gha/chunks/550.per-chunk-artifacts_job.yaml
+++ b/userpatches-jethub/gha/chunks/550.per-chunk-artifacts_job.yaml
@@ -58,43 +58,44 @@ jobs: # <TEMPLATE-IGNORE>
       - name: Build  ${{matrix.desc}}
         id: build
         run: |
-          bash ./compile.sh ${{ matrix.invocation }} SHARE_LOG=yes ${{env.EXTRA_PARAMS_ALL_BUILDS}}
+          bash ./compile.sh ${{ matrix.invocation }} REVISION="${{ needs.matrix_prep.outputs.version }}" SHARE_LOG=yes ${{env.EXTRA_PARAMS_ALL_BUILDS}} ${{env.EXTRA_PARAMS_ALL_BUILDS}}
+          # UPLOAD_TO_OCI_ONLY=yes
 
       - name: "Logs: ${{ steps.build.outputs.logs_url }}"
         if: always()
         run: |
           echo "Logs: ${{ steps.build.outputs.logs_url }}"
 
-      - name: Check API rate limits
-        run: |
+#      - name: Check API rate limits
+#        run: |
 
-          # install dependencies
-          if ! command -v "gh" > /dev/null 2>&1; then
-             type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
-             curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
-             && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
-             && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-             && sudo apt update \
-             && sudo apt install gh -y
-          fi
+#          # install dependencies
+#          if ! command -v "gh" > /dev/null 2>&1; then
+#             type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
+#             curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
+#             && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
+#             && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
+#             && sudo apt update \
+#             && sudo apt install gh -y
+#          fi
 
-          while true
-            do
-            API_CALLS_TOTAL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit | jq -r '.rate.limit')
-            API_CALLS_LEFT=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit | jq -r '.rate.remaining')
-            PERCENT=$(( API_CALLS_LEFT * 100 / API_CALLS_TOTAL ))
-            if (( $PERCENT > 30 )); then
-                echo "API rate in good shape $PERCENT % free"
-                exit 0
-            fi
-            echo "API rate lower then 30%, sleping 10m"
-            sleep 10m
-          done
-
-          # show current api rate
-          curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
-
-      - name: "Cleanup artefacts"
-        if: always()
-        run: sudo rm -rfv output/debs
+#          while true
+#            do
+#            API_CALLS_TOTAL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit | jq -r '.rate.limit')
+#            API_CALLS_LEFT=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /rate_limit | jq -r '.rate.remaining')
+#            PERCENT=$(( API_CALLS_LEFT * 100 / API_CALLS_TOTAL ))
+#            if (( $PERCENT > 30 )); then
+#                echo "API rate in good shape $PERCENT % free"
+#                exit 0
+#            fi
+#            echo "API rate lower then 30%, sleping 10m"
+#            sleep 10m
+#          done
+#
+#          # show current api rate
+#          curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
+#
+#      - name: "Cleanup artefacts"
+#        if: always()
+#        run: sudo rm -rfv output/debs
 
